name: Windows MacOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies others
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    # Windows is treated differently, as PyTorch is not uploaded to Pypi atm
    - name: Install dependencies windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        python -m pip install --upgrade pip
        pip install .[dev] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lint with Black
      run: |
        black --check --diff .

    - name: Test with pytest
      run: |
        pytest test
